#!/usr/bin/with-contenv bash
set -e

if (( ${SENTINEL_IS_ACTIVE} == 1 )) || [ "${SENTINEL_IS_ACTIVE}" = "true" ]; then
	# MAP UID/GID
	USERMAP_UID=${USERMAP_UID:-redis}
	USERMAP_GID=${USERMAP_GID:-redis}

	if [[ $USERMAP_UID != *[[:digit:]]* ]]; then
		USERMAP_UID=$(id -u $USERMAP_UID)
	fi

	if [[ $USERMAP_GID != *[[:digit:]]* ]]; then
		USERMAP_GID=$(id -g $USERMAP_GID)
	fi

	chown ${USERMAP_UID}:${USERMAP_GID} /etc/sentinel.conf
	chmod 0775 /etc/sentinel.conf
	
	sleep 10
	
	exec s6-applyuidgid -u ${USERMAP_UID} -g ${USERMAP_GID} redis-server /etc/sentinel.conf --sentinel
fi
