#!/usr/bin/with-contenv bash
set -e

REDIS_PASSWORD=${REDIS_PASSWORD:-}
REDIS_MAXCLIENTS=${REDIS_MAXCLIENTS:-1024}

# Set Max Clients
sed "s/^maxclients.*/maxclients ${REDIS_MAXCLIENTS}/" -i /etc/redis.conf

# MAP UID/GID
USERMAP_UID=${USERMAP_UID:-redis}
USERMAP_GID=${USERMAP_GID:-redis}

RUN_UID_GID="${USERMAP_UID}:${USERMAP_GID}"
if [ ${PG_UID} = "redis" ] && [ ${PG_GID} = "redis" ]; then
	RUN_UID_GID=postgres
fi 

exec s6-setuidgid ${RUN_UID_GID} redis-server /etc/redis.conf ${REDIS_PASSWORD:+--requirepass $REDIS_PASSWORD};