#!/usr/bin/with-contenv bash

# MAP UID/GID
USERMAP_UID=${USERMAP_UID:-redis}
USERMAP_GID=${USERMAP_GID:-redis}

if [[ $USERMAP_UID != *[[:digit:]]* ]]; then
	USERMAP_UID=$(id -u $USERMAP_UID)
fi

if [[ $USERMAP_GID != *[[:digit:]]* ]]; then
	USERMAP_GID=$(id -g $USERMAP_GID)
fi

chown -R ${USERMAP_UID}:${USERMAP_GID} /var/lib/redis
chown -R ${USERMAP_UID}:${USERMAP_GID} /var/log/redis
chown -R ${USERMAP_UID}:${USERMAP_GID} /var/run/redis
