#!/usr/bin/with-contenv bash
set -e

REDIS_MIN_SLAVES_TO_WRITE=${REDIS_MIN_SLAVES_TO_WRITE:-0}
REDIS_MIN_SLAVES_MAX_LAG=${REDIS_MIN_SLAVES_MAX_LAG:-10}

if (( ${REDIS_MIN_SLAVES_TO_WRITE} > 0 )); then
	sed "s/^# min-slaves-to-write.*/min-slaves-to-write ${REDIS_MIN_SLAVES_TO_WRITE}/" -i /etc/redis.conf
	sed "s/^# min-slaves-max-lag.*/min-slaves-to-write ${REDIS_MIN_SLAVES_TO_WRITE}/" -i /etc/redis.conf
fi
