#!/usr/bin/with-contenv bash
set -e

REDIS_SLAVE=${REDIS_SLAVE:-0}
REDIS_SLAVE_ANNOUNCE_IP=${REDIS_SLAVE_ANNOUNCE_IP:-}
REDIS_SLAVE_ANNOUNCE_PORT=${REDIS_SLAVE_ANNOUNCE_PORT:-}
REDIS_MASTER_HOST=${REDIS_MASTER_HOST:-}
REDIS_MASTER_PORT=${REDIS_MASTER_PORT:-6379}
REDIS_MASTER_PASSWORD=${REDIS_MASTER_PASSWORD:-}

if (( ${REDIS_SLAVE} == 1 )) || [ "${REDIS_SLAVE}" = "true" ]; then

	if [ -z "$REDIS_MASTER_HOST" ]; then
		echo "Missing REDIS_MASTER_HOST"
		exit 1
	fi
	
	if [ -z "$REDIS_MASTER_PORT" ]; then
		echo "Missing REDIS_MASTER_PORT"
		exit 1
	fi
	
	if [ -n "$REDIS_SLAVE_ANNOUNCE_IP" ]; then
		sed "s/^# slave-announce-ip.*/slave-announce-ip ${REDIS_SLAVE_ANNOUNCE_IP}/" -i /etc/redis.conf
		sed "s/^slave-announce-ip.*/slave-announce-ip ${REDIS_SLAVE_ANNOUNCE_IP}/" -i /etc/redis.conf
	fi
	
	if [ -n "$REDIS_SLAVE_ANNOUNCE_PORT" ]; then
		sed "s/^# slave-announce-port.*/slave-announce-port ${REDIS_SLAVE_ANNOUNCE_PORT}/" -i /etc/redis.conf
		sed "s/^slave-announce-port.*/slave-announce-port ${REDIS_SLAVE_ANNOUNCE_PORT}/" -i /etc/redis.conf
	fi
	
	sed "s/^# slaveof.*/slaveof ${REDIS_MASTER_HOST} ${REDIS_MASTER_PORT}/" -i /etc/redis.conf
	sed "s/^slaveof.*/slaveof ${REDIS_MASTER_HOST} ${REDIS_MASTER_PORT}/" -i /etc/redis.conf
fi

# force set of masterauth, needed when master becomes slave after failover
if [ -n "$REDIS_MASTER_PASSWORD" ]; then
	sed "s/^# masterauth.*/masterauth ${REDIS_MASTER_PASSWORD}/" -i /etc/redis.conf
	sed "s/^masterauth.*/masterauth ${REDIS_MASTER_PASSWORD}/" -i /etc/redis.conf
fi
